### ISSUE TITLE
Angular component?

### ISSUE THREAD

**Issue by jdnichollsc** [felicegattuso/timedropper#4]
Hi man,

This plugin is excellent, what do you think to migrate to Angular? maybe to use with Ionic apps.

Regards, Nicholls

**Comment by hayatnoor** [comment]
I've created an angular directive for this plugin here:

https://github.com/hayatnoor/angular-timedropper

**Comment by pinrostudio** [comment]
Please have a look at this

https://github.com/pinrostudio/angular-timedropper

**JSBin:**
 (http://output.jsbin.com/ziyipeh)

**Comment by jdnichollsc** [comment]
Beautiful! :dancers:
